/**************************************************************************
 * C S 429 system emulator
 * 
 * instr_Decode.c - Decode stage of instruction processing pipeline.
 **************************************************************************/ 

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <assert.h>
#include "err_handler.h"
#include "instr.h"
#include "instr_pipeline.h"
#include "forward.h"
#include "machine.h"
#include "hw_elts.h"

#define SP_NUM 31
#define XZR_NUM 32

extern machine_t guest;
extern mem_status_t dmem_status;

extern int64_t W_wval;

/*
 * Control signals for D, X, M, and W stages.
 * Generated by D stage logic.
 * D control signals are consumed locally. 
 * Others must be buffered in pipeline registers.
 * STUDENT TO-DO:
 * Generate the correct control signals for this instruction's
 * future stages and write them to the corresponding struct.
 */

static comb_logic_t 
generate_DXMW_control(opcode_t op,
                      d_ctl_sigs_t *D_sigs, x_ctl_sigs_t *X_sigs, m_ctl_sigs_t *M_sigs, w_ctl_sigs_t *W_sigs) {

    // D control signal
    D_sigs->src2_sel = op == OP_STUR ? true : false;

    // X control signals
    if (op == OP_ADDS_RR || op == OP_ANDS_RR || op == OP_SUBS_RR || op == OP_CMP_RR || op == OP_TST_RR ||
        op == OP_ORR_RR || op == OP_EOR_RR || op == OP_MVN || op == OP_CSEL || op == OP_CSINC || op == OP_CSINV ||
        op == OP_CSNEG) {
        X_sigs->valb_sel = true;
    } else {
        X_sigs->valb_sel = false;
    }

    if (op == OP_ADDS_RR || op == OP_ANDS_RR || op == OP_SUBS_RR || op == OP_CMP_RR || op == OP_TST_RR) {
        X_sigs->set_CC = true;
    } else {
        X_sigs->set_CC = false;
    }

    // M control signals
    M_sigs->dmem_read = op == OP_LDUR ? true : false;
    M_sigs->dmem_write = op == OP_STUR ? true : false;

    // W control signals
    if (op == OP_BL || op == OP_BLR) {
        W_sigs->dst_sel = true;
    } else {
        W_sigs->dst_sel = false;
    }
    
    W_sigs->wval_sel = op == OP_LDUR ? true : false;

    if (op != OP_STUR && op != OP_B && op != OP_B_COND && op != OP_RET && op != OP_NOP && op != OP_HLT &&
        op != OP_CMP_RR && op != OP_TST_RR && op != OP_BR && op != OP_CBZ && op != OP_CBNZ) {
            W_sigs->w_enable = true;
        } else {
            W_sigs->w_enable = false;
        }
}

/*
 * Logic for extracting the immediate value for M-, I-, and RI-format instructions.
 * STUDENT TO-DO:
 * Extract the immediate value and write it to *imm.
 */

static comb_logic_t 
extract_immval(uint32_t insnbits, opcode_t op, int64_t *imm) {
    
    // Switch on op
    switch(op) {

        // M-format instructions:
        // LDUR
        case OP_LDUR:
            *imm = bitfield_s64(insnbits, 12, 9);
            break;

        // STUR
        case OP_STUR:
            *imm = bitfield_s64(insnbits, 12, 9);
            break;

        // I-format instructions
        // MOVK
        case OP_MOVK:

        // MOVZ
        case OP_MOVZ:
            *imm = bitfield_u32(insnbits, 5, 16);
            break;

        // ADRP
        case OP_ADRP:
            *imm = ((bitfield_s64(insnbits, 5, 19) << 2) | bitfield_s64(insnbits, 29, 2)) << 12;
            break;

        // RI-format instructions
        // ADD
        case OP_ADD_RI:
            *imm = bitfield_u32(insnbits, 10, 12);
            break;

        // SUB
        case OP_SUB_RI:
            *imm = bitfield_u32(insnbits, 10, 12);
            break;

        // LSL
        case OP_LSL:
            *imm = 64 - bitfield_u32(insnbits, 16, 6);
            break;  

        // LSR
        case OP_LSR:
            *imm = bitfield_u32(insnbits, 16, 6);
            break;

        // ASR
        case OP_ASR:
            *imm = bitfield_u32(insnbits, 16, 6);
            break;

        default:
            break;
    }
}

/*
 * Logic for determining the ALU operation needed for this opcode.
 * STUDENT TO-DO:
 * Determine the ALU operation based on the given opcode
 * and write it to *ALU_op.
 */
static comb_logic_t
decide_alu_op(opcode_t op, alu_op_t *ALU_op) {
    
    // Switch on op
    switch(op) {
        
        // LDUR
        case OP_LDUR:

        // STUR
        case OP_STUR:

        // ADRP
        case OP_ADRP:

        // ADD
        case OP_ADD_RI:

        // ADDS
        case OP_ADDS_RR:
            *ALU_op = PLUS_OP;
            break;

        // CMP
        case OP_CMP_RR:

        // SUB
        case OP_SUB_RI:

        // SUBS
        case OP_SUBS_RR:
            *ALU_op = MINUS_OP;
            break;

        // INV
        case OP_MVN:
            *ALU_op = INV_OP;
            break;

        // ORR
        case OP_ORR_RR:
            *ALU_op = OR_OP;
            break;

        // EOR
        case OP_EOR_RR:
            *ALU_op = EOR_OP;
            break;

        // TST
        case OP_TST_RR:

        // AND
        case OP_ANDS_RR:
            *ALU_op = AND_OP;
            break;

        // MOVK
        case OP_MOVK:

        // MOVZ
        case OP_MOVZ:
            *ALU_op = MOV_OP;
            break;

        // LSL
        case OP_LSL:
            *ALU_op = LSL_OP;
            break;

        // LSR
        case OP_LSR:
            *ALU_op = LSR_OP;
            break;
            
        // ASR
        case OP_ASR:
            *ALU_op = ASR_OP;
            break;

        // CSEL
        case OP_CSEL:
            *ALU_op = CSEL_OP;
            break;

        // CSINV
        case OP_CSINV:
            *ALU_op = CSINV_OP;
            break;

        // CSINC
        case OP_CSINC:
            *ALU_op = CSINC_OP;
            break;

        // CSNEG
        case OP_CSNEG:
            *ALU_op = CSNEG_OP;
            break;

        // CBZ
        case OP_CBZ:
            *ALU_op = CBZ_OP;
            break;

        // CBNZ
        case OP_CBNZ:
            *ALU_op = CBNZ_OP;
            break;

        // All other instructons
        default:
            *ALU_op = PASS_A_OP;
            break;
    }
}

/*
 * Utility functions for copying over control signals across a stage.
 * STUDENT TO-DO:
 * Copy the input signals from the input side of the pipeline
 * register to the output side of the register.
 */

comb_logic_t 
copy_m_ctl_sigs(m_ctl_sigs_t *dest, m_ctl_sigs_t *src) {
    dest->dmem_read = src->dmem_read ? true : false;
    dest->dmem_write = src->dmem_write ? true : false;
}

comb_logic_t 
copy_w_ctl_sigs(w_ctl_sigs_t *dest, w_ctl_sigs_t *src) {
    dest->dst_sel = src->dst_sel ? true : false;
    dest->wval_sel = src->wval_sel ? true : false;
    dest->w_enable = src->w_enable ? true : false;
}

comb_logic_t
extract_regs(uint32_t insnbits, opcode_t op, 
             uint8_t *src1, uint8_t *src2, uint8_t *dst) {

    // Destination register
    *dst = bitfield_u32(insnbits, 0, 5);

    // src1
    *src1 = bitfield_u32(insnbits, 5, 5);

    // src2
    *src2 = bitfield_u32(insnbits, 16, 5);

    // Handle dst
    if (*dst == SP_NUM && (op == OP_LDUR || op == OP_STUR || op == OP_MOVK || op == OP_MOVZ || op == OP_ADRP || op == OP_ADDS_RR || op == OP_SUBS_RR || op == OP_CMP_RR || op == OP_MVN || op == OP_ANDS_RR || op == OP_TST_RR || op == OP_LSL || op == OP_LSR || op == OP_UBFM || op == OP_ASR || op == OP_EOR_RR)) {
        *dst = XZR_NUM;
    }

    // Handle src1
    if (*src1 == SP_NUM && (op != OP_LDUR && op != OP_STUR && op != OP_ADD_RI && op != OP_SUB_RI)) {
        *src1 = XZR_NUM;
    }
    
    // Handle src2
    if (*src2 == SP_NUM) {
        *src2 = XZR_NUM;
    }

    // Handle single src instructions
    if (op == OP_ADD_RI || op == OP_SUB_RI || op == OP_LSL || op == OP_LSR || op == OP_ASR || op == OP_MOVZ || op == OP_MOVK) {
        *src2 = XZR_NUM;
    }
}

/*
 * Decode stage logic.
 * STUDENT TO-DO:
 * Implement the decode stage.
 * 
 * Use `in` as the input pipeline register,
 * and update the `out` pipeline register as output.
 * Additionally, make sure the register file is updated
 * with W_out's output when you call it in this stage.
 * 
 * You will also need the following helper functions:
 * generate_DXMW_control, regfile, extract_immval,
 * and decide_alu_op.
 */

comb_logic_t decode_instr(d_instr_impl_t *in, x_instr_impl_t *out) {
    
    // Pass existing fields
    out->op = in->op;
    out->print_op = in->print_op;
    out->seq_succ_PC = in->seq_succ_PC;
    out->status = in->status;

    // Control signals
    d_ctl_sigs_t D_sigs;
    generate_DXMW_control(in->op, &D_sigs, &(out->X_sigs), &(out->M_sigs), &(out->W_sigs));

    // ALU op
    decide_alu_op(in->op, &(out->ALU_op));

    // Cond
    if (in->op == OP_B_COND) {
        out->cond = bitfield_u32(in->insnbits, 0, 4);
    } else if (in->op == OP_CSEL || in->op == OP_CSINV || in->op == OP_CSINC || in->op == OP_CSNEG) {
        out->cond = bitfield_u32(in->insnbits, 12, 4);
    }

    // Immediate and hw
    extract_immval(in->insnbits, in->op, &(out->val_imm));
    if (in->op == OP_MOVK || in->op == OP_MOVZ) {
        out->val_hw = bitfield_u32(in->insnbits, 21, 2) << 4;
    } else {
        out->val_hw = 0;
    }

    // Register extraction and regfile
    uint8_t src1, src2;
    extract_regs(in->insnbits, in->op, &src1, &src2, &(out->dst));
    if (D_sigs.src2_sel == true) {
        src2 = bitfield_u32(in->insnbits, 0, 5);
    } else if (out->W_sigs.dst_sel == true) {
        out->dst = 30;
    }  
    if (out->op == OP_MOVK || out->op == OP_CBZ || out->op == OP_CBNZ) {
        src1 = out->dst;
    } 

    regfile(src1, src2, W_out->dst, W_wval, W_out->W_sigs.w_enable, &(out->val_a), &(out->val_b));

    if (out->op == OP_STUR && out->val_b == guest.proc->SP) {
        out->val_b = 0;
    }

    if (in->op == OP_BL || in->op == OP_BLR) {
        out->val_a = in->seq_succ_PC;
    } 

    // Forward values for PIPE implementation
    forward_reg(src1, src2, M_in->dst, W_in->dst, W_out->dst, M_in->val_ex, W_in->val_ex, W_in->val_mem, W_out->val_ex, W_out->val_mem,
                W_in->W_sigs.wval_sel, W_out->W_sigs.wval_sel, M_in->W_sigs.w_enable, W_in->W_sigs.w_enable, 
                W_out->W_sigs.w_enable, &(out->val_a), &(out->val_b));

    // Specifically for MOVK
    if (out->op == OP_MOVK) {
        uint64_t temp = 0xFFFF;
        temp = temp << out->val_hw;
        temp = ~temp;
        out->val_a &= temp;
    } else if (out->op == OP_MOVZ) {
        out->val_a = 0;
    } else if (in->op == OP_ADDS_RR || in->op == OP_SUBS_RR || in->op == OP_CMP_RR) {
        int shift = bitfield_u32(in->insnbits, 22, 2);
        uint16_t shiftAMT = bitfield_u32(in->insnbits, 10, 6);
        if (shift == 0) {
            out->val_b = out->val_b << shiftAMT;
        } else if (shift == 1) {
            out->val_b = out->val_b >> shiftAMT;
        } else {
            out->val_b = (signed) out->val_b >> shiftAMT; 
        }
        out->val_hw = 0;
    }

    // Specifically for ADRP
    if (in->op == OP_ADRP) {
        out->val_a = in->adrp_val;
        out->val_b = 0;
    }
    
}
